export const lessonplan = [
  {
    title: "Lesson Plan 1",
    tags: ["Assignment", "6th class", "Section B"],
    date: "21-July to 21 Sept",
    language: "English",
    students: "50",
    subject: "English",
    day: "day 1",
    duration: "10 mins",
  },
  {
    title: "Lesson plan 2",
    tags: ["Test", "7th class", "Section B"],
    date: "21-July to 21 Sept",
    language: "English",
    students: "50",
    subject: "English",
    day: "day 1",
    duration: "10 mins",
  },
  {
    title: "Lesson plan 3",
    tags: ["practical", "9th class", "All Sections"],
    date: "21-July to 21 Sept",
    language: "English",
    students: "50",
    subject: "English",
    day: "day 1",
    duration: "10 mins",
  },
  {
    title: "Lesson plan 4",
    tags: ["Exam", "3rd class", "Section A"],
    date: "21-July to 21 Sept",
    language: "English",
    students: "50",
    subject: "English",
    day: "day 1",
    duration: "10 mins",
  },
];
