import {
  missingHeart,
  marketBeats,
  lionWitch,
  lifeBoat,
  perc,
  WildCall,
} from "../Constant/images";
export const books = [
  {
    thumbnail: missingHeart,
    title: "Our Missing Hearts",
    author: "Celeste",
    pages: 150,
    duration: null,
    stars: 4,
    ratings: 1.2,
  },
  {
    thumbnail: WildCall,
    title: "The Call of the Wild          ",
    author: "Jack London",
    pages: null,
    duration: 5,
    stars: 5,
    ratings: 1.2,
  },
  {
    thumbnail: marketBeats,
    title: "The beats of the market  ",
    author: "Jack London",
    pages: null,
    duration: 5,
    stars: 3.5,
    ratings: 1.2,
  },
  {
    thumbnail: lionWitch,
    title: "The Lion of the witch",
    author: "C.S Lewis ",
    pages: 150,
    duration: null,
    stars: 4.5,
    ratings: 1.2,
  },
  {
    thumbnail: perc,
    title: "Perc jackson",
    author: "Celeste",
    pages: 150,
    duration: null,
    stars: 3.5,
    ratings: 1.2,
  },
  {
    thumbnail: lifeBoat,
    title: "The Life boat",
    author: "charlotte rogan",
    pages: null,
    duration: 5,
    stars: 5,
    ratings: 1.2,
  },
];
