export const books = [
  {
    thumbnail: "http://surl.li/rkxin",
    title: "Our Missing Hearts",
    author: "Celeste",
    pages: 150,
    duration: null,
    stars: 5,
    ratings: 1.2,
  },
  {
    thumbnail: "http://surl.li/rkyjd",
    title: "The Call of the Wild          ",
    author: "Jack London",
    pages: null,
    duration: 5,
    stars: 5,
    ratings: 1.2,
  },
  {
    thumbnail: "http://surl.li/rkyjv",
    title: "The beats of the market  ",
    author: "Jack London",
    pages: null,
    duration: 5,
    stars: 5,
    ratings: 1.2,
  },
  {
    thumbnail: "http://surl.li/rkyki",
    title: "The Lion of the witch",
    author: "C.S Lewis ",
    pages: 150,
    duration: null,
    stars: 5,
    ratings: 1.2,
  },
  {
    thumbnail: "http://surl.li/rkykw",
    title: "Perc jackson",
    author: "Celeste",
    pages: 150,
    duration: null,
    stars: 5,
    ratings: 1.2,
  },
  {
    thumbnail: "http://surl.li/rkyle",
    title: "The Life boat",
    author: "charlotte rogan",
    pages: null,
    duration: 5,
    stars: 5,
    ratings: 1.2,
  },
];
